### ISSUE TITLE
Marketplace: Align on which versions of SpinKube projects to ship and update CNAB bundle accordingly (if necessary)

### ISSUE THREAD

**Issue by macolso** [spinkube/azure#30]
I believe the two main projects that are likely to have updates in the next two weeks are spin operator and potentially shim?  I would be in favor of including the latest spin operator release so marketplace users can take advantage of the newest features.

- [x] spin operator v0.4. - tracked in https://github.com/spinkube/spin-operator/issues/336
  -> https://github.com/spinkube/azure/pull/33
  -> Shipped in 1.2.1, published to the Marketplace on 11/11/24
- [x] containerd-spin-shim v0.17
  -> Due to ship in the next 1.3.0 release (ref https://github.com/spinkube/azure/pull/42)

**Comment by macolso** [comment]
@kate-goldenring - do you know if there are plans to release a new shim version in the next week or so?

**Comment by kate-goldenring** [comment]
Yes. We were planning to cut the shim after the Spin 3.0 release, targeting that stable version of spin dependencies.

**Comment by macolso** [comment]
Ok, that would be good to include as well! I believe that would be v0.17.0 for the shim.

**Comment by macolso** [comment]
@vdice - do we need to plan on including a new version of kwasm that includes the fix you're working on in [#222](https://github.com/spinkube/runtime-class-manager/issues/222)

**Comment by vdice** [comment]
@macolso note that https://github.com/spinkube/runtime-class-manager/issues/222 is part of the newer [runtime-class-manager](https://github.com/spinkube/runtime-class-manager/) project, not kwasm-operator.  Beyond this work, RCM still needs at least a bit of [CD work](https://github.com/spinkube/runtime-class-manager/issues/236) (chart distribution and releasing) before we can swap that in for kwasm-operator in SpinKube for the marketplace.  Those are the two main items top of mind.  So not sure if that will make timeline(s).

If we release the marketplace offering with kwasm-operator still included (and assuming spin-operator 0.4 and shim 0.17), a next release with RCM swapped in _should_ be additive and non-breaking... but we'll want to test this upgrade thoroughly.  I just spent an hour in a helm rabbit hole around this and we may need to implement some more hook-based logic to work around current helm limitations to ensure the new rcm CRD(s) are installed... but an effort for another day.

**Comment by macolso** [comment]
Got it. I misunderstood the second bullet in [spinkube/runtime-class-manager#222](https://github.com/spinkube/runtime-class-manager/issues/222) (thought it was a kwasm workaround). Thanks for clarifying. For marketplace release's sake, I agree we should go with kwasm-operator to start and then re-evaluate later in November with the additive swap approach you're suggesting.

**Comment by vdice** [comment]
The latest 1.3.0 Marketplace version has been published containing all of the dependency versions spec'd in the original description.  Closing.
